Feature/file list
ICEI-PUC-Minas-PPLES-TI/plf-es-2023-1-tcci-0393100-dev-gitgrade pull request #234
Opened 2023-10-23 03:01 UTC by guizombas

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

closes #201 
closes #199

2023-10-23 03:03 UTC, guizombas commented
-- estou retornando os contribuidores que contribuíram em cada commit da página, porém ficou bem pesado a busca. Tentei fazer alguma otimização, mas acho que seria um pouco mais complexo. Provavelmente vou remover essa informação.

2023-10-23 03:25 UTC, Lucas-Angelo commented
> -- estou retornando os contribuidores que contribuíram em cada commit da página, porém ficou bem pesado a busca. Tentei fazer alguma otimização, mas acho que seria um pouco mais complexo. Provavelmente vou remover essa informação.

Faz sentido ficar pesada, talvez deixar isso como uma opção se quiser trazer junto

2023-10-23 17:36 UTC, guizombas commented
Fiz isso, agora ficou show

2023-10-23 20:59 UTC, Lucas-Angelo requested changes
Deu erro:

![image](https://github.com/ICEI-PUC-Minas-PPLES-TI/plf-es-2023-1-tcci-0393100-dev-plataformaapoioavaliacoesprojetos/assets/49598959/65f155e2-47b2-40db-94e7-649d54b3375f)

supportplatform-service
```js
2023-10-23 17:56:03 [ERROR]: Error finding all files: {
  "error": {
    "name": "SequelizeDatabaseError",
    "parent": {
      "code": "ER_WRONG_FIELD_WITH_GROUP",
      "errno": 1055,
      "sqlState": "42000",
      "sqlMessage": "Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'gitgrade.File.extension' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by",
      "sql": "SELECT `File`.`path`, `File`.`extension`, SUM(`additions`) AS `additions`, SUM(`deletions`) AS `deletions`, `commit`.`id` AS `commit.id`, `commit`.`committed_date` AS `commit.committedDate`, `commit->branch`.`name` AS `commit.branch.name`, `commit->branch`.`id` AS `commit.branch.id`, `commit->contributor`.`id` AS `commit.contributor.id`, `commit->contributor`.`github_name` AS `commit.contributor.githubName`, `commit->contributor`.`github_login` AS `commit.contributor.githubLogin`, `commit->contributor`.`github_avatar_url` AS `commit.contributor.githubAvatarUrl`, `commit->contributor`.`github_email` AS `commit.contributor.githubEmail` FROM `file` AS `File` LEFT OUTER JOIN `commit` AS `commit` ON `File`.`commit_id` = `commit`.`id` LEFT OUTER JOIN `branch` AS `commit->branch` ON `commit`.`branch_id` = `commit->branch`.`id` LEFT OUTER JOIN `contributor` AS `commit->contributor` ON `commit`.`contributor_id` = `commit->contributor`.`id` WHERE (`commit->branch`.`repository_id` = 274 AND `commit->branch`.`name` = 'master') GROUP BY `path` ORDER BY `File`.`path` ASC LIMIT 0, 5;"
    },
    "original": {
      "code": "ER_WRONG_FIELD_WITH_GROUP",
      "errno": 1055,
      "sqlState": "42000",
      "sqlMessage": "Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'gitgrade.File.extension' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by",
      "sql": "SELECT `File`.`path`, `File`.`extension`, SUM(`additions`) AS `additions`, SUM(`deletions`) AS `deletions`, `commit`.`id` AS `commit.id`, `commit`.`committed_date` AS `commit.committedDate`, `commit->branch`.`name` AS `commit.branch.name`, `commit->branch`.`id` AS `commit.branch.id`, `commit->contributor`.`id` AS `commit.contributor.id`, `commit->contributor`.`github_name` AS `commit.contributor.githubName`, `commit->contributor`.`github_login` AS `commit.contributor.githubLogin`, `commit->contributor`.`github_avatar_url` AS `commit.contributor.githubAvatarUrl`, `commit->contributor`.`github_email` AS `commit.contributor.githubEmail` FROM `file` AS `File` LEFT OUTER JOIN `commit` AS `commit` ON `File`.`commit_id` = `commit`.`id` LEFT OUTER JOIN `branch` AS `commit->branch` ON `commit`.`branch_id` = `commit->branch`.`id` LEFT OUTER JOIN `contributor` AS `commit->contributor` ON `commit`.`contributor_id` = `commit->contributor`.`id` WHERE (`commit->branch`.`repository_id` = 274 AND `commit->branch`.`name` = 'master') GROUP BY `path` ORDER BY `File`.`path` ASC LIMIT 0, 5;"
    },
    "sql": "SELECT `File`.`path`, `File`.`extension`, SUM(`additions`) AS `additions`, SUM(`deletions`) AS `deletions`, `commit`.`id` AS `commit.id`, `commit`.`committed_date` AS `commit.committedDate`, `commit->branch`.`name` AS `commit.branch.name`, `commit->branch`.`id` AS `commit.branch.id`, `commit->contributor`.`id` AS `commit.contributor.id`, `commit->contributor`.`github_name` AS `commit.contributor.githubName`, `commit->contributor`.`github_login` AS `commit.contributor.githubLogin`, `commit->contributor`.`github_avatar_url` AS `commit.contributor.githubAvatarUrl`, `commit->contributor`.`github_email` AS `commit.contributor.githubEmail` FROM `file` AS `File` LEFT OUTER JOIN `commit` AS `commit` ON `File`.`commit_id` = `commit`.`id` LEFT OUTER JOIN `branch` AS `commit->branch` ON `commit`.`branch_id` = `commit->branch`.`id` LEFT OUTER JOIN `contributor` AS `commit->contributor` ON `commit`.`contributor_id` = `commit->contributor`.`id` WHERE (`commit->branch`.`repository_id` = 274 AND `commit->branch`.`name` = 'master') GROUP BY `path` ORDER BY `File`.`path` ASC LIMIT 0, 5;",
    "parameters": {}
  }
}
2023-10-23 17:56:03 [ERROR]: Error:  Failed to find all files {
  "name": "AppError",
  "statusCode": 500,
  "error": {
    "name": "SequelizeDatabaseError",
    "parent": {
      "code": "ER_WRONG_FIELD_WITH_GROUP",
      "errno": 1055,
      "sqlState": "42000",
      "sqlMessage": "Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'gitgrade.File.extension' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by",
      "sql": "SELECT `File`.`path`, `File`.`extension`, SUM(`additions`) AS `additions`, SUM(`deletions`) AS `deletions`, `commit`.`id` AS `commit.id`, `commit`.`committed_date` AS `commit.committedDate`, `commit->branch`.`name` AS `commit.branch.name`, `commit->branch`.`id` AS `commit.branch.id`, `commit->contributor`.`id` AS `commit.contributor.id`, `commit->contributor`.`github_name` AS `commit.contributor.githubName`, `commit->contributor`.`github_login` AS `commit.contributor.githubLogin`, `commit->contributor`.`github_avatar_url` AS `commit.contributor.githubAvatarUrl`, `commit->contributor`.`github_email` AS `commit.contributor.githubEmail` FROM `file` AS `File` LEFT OUTER JOIN `commit` AS `commit` ON `File`.`commit_id` = `commit`.`id` LEFT OUTER JOIN `branch` AS `commit->branch` ON `commit`.`branch_id` = `commit->branch`.`id` LEFT OUTER JOIN `contributor` AS `commit->contributor` ON `commit`.`contributor_id` = `commit->contributor`.`id` WHERE (`commit->branch`.`repository_id` = 274 AND `commit->branch`.`name` = 'master') GROUP BY `path` ORDER BY `File`.`path` ASC LIMIT 0, 5;"
    },
    "original": {
      "code": "ER_WRONG_FIELD_WITH_GROUP",
      "errno": 1055,
      "sqlState": "42000",
      "sqlMessage": "Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'gitgrade.File.extension' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by",
      "sql": "SELECT `File`.`path`, `File`.`extension`, SUM(`additions`) AS `additions`, SUM(`deletions`) AS `deletions`, `commit`.`id` AS `commit.id`, `commit`.`committed_date` AS `commit.committedDate`, `commit->branch`.`name` AS `commit.branch.name`, `commit->branch`.`id` AS `commit.branch.id`, `commit->contributor`.`id` AS `commit.contributor.id`, `commit->contributor`.`github_name` AS `commit.contributor.githubName`, `commit->contributor`.`github_login` AS `commit.contributor.githubLogin`, `commit->contributor`.`github_avatar_url` AS `commit.contributor.githubAvatarUrl`, `commit->contributor`.`github_email` AS `commit.contributor.githubEmail` FROM `file` AS `File` LEFT OUTER JOIN `commit` AS `commit` ON `File`.`commit_id` = `commit`.`id` LEFT OUTER JOIN `branch` AS `commit->branch` ON `commit`.`branch_id` = `commit->branch`.`id` LEFT OUTER JOIN `contributor` AS `commit->contributor` ON `commit`.`contributor_id` = `commit->contributor`.`id` WHERE (`commit->branch`.`repository_id` = 274 AND `commit->branch`.`name` = 'master') GROUP BY `path` ORDER BY `File`.`path` ASC LIMIT 0, 5;"
    },
    "sql": "SELECT `File`.`path`, `File`.`extension`, SUM(`additions`) AS `additions`, SUM(`deletions`) AS `deletions`, `commit`.`id` AS `commit.id`, `commit`.`committed_date` AS `commit.committedDate`, `commit->branch`.`name` AS `commit.branch.name`, `commit->branch`.`id` AS `commit.branch.id`, `commit->contributor`.`id` AS `commit.contributor.id`, `commit->contributor`.`github_name` AS `commit.contributor.githubName`, `commit->contributor`.`github_login` AS `commit.contributor.githubLogin [...]

2023-10-24 01:30 UTC, Lucas-Angelo approved these changes

2023-10-24 01:30 UTC, merged