Feature/repo config
ICEI-PUC-Minas-PPLES-TI/plf-es-2023-1-tcci-0393100-dev-gitgrade pull request #242
Opened 2023-10-25 04:04 UTC by guizombas

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

closes #208 
closes #209 
closes #210 
closes #215 
closes #212

2023-10-28 10:29 UTC, Lucas-Angelo requested changes
- Adicionar em todas as opções: “você realmente deseja fazer isso” na tela de config de repositório

2023-10-28 10:29 UTC, Lucas-Angelo commented on Codigo/supportplatform-service/src/service/BranchService.ts
>              const { rows, count } = await Branch.findAndCountAll({
Adicionar orderBy commitAutomaticSynchronization e fileAutomaticSynchronization

2023-10-28 10:29 UTC, Lucas-Angelo commented on Codigo/supportplatform-service/src/test/controller/BranchController.test.ts
> +describe("PATCH /repository/{id}/branch/{branchId}", () => {
Só 1 dúvida, para PATCH de automatic_sync do /repository já tem teste?

2023-10-28 15:27 UTC, guizombas commented on Codigo/supportplatform-service/src/test/controller/BranchController.test.ts
> +describe("PATCH /repository/{id}/branch/{branchId}", () => {
tem, ce já tinha feito
![image](https://github.com/ICEI-PUC-Minas-PPLES-TI/plf-es-2023-1-tcci-0393100-dev-plataformaapoioavaliacoesprojetos/assets/63319368/4b89cd58-93e8-463d-bf8b-daa96787247a)

2023-10-29 17:41 UTC, Lucas-Angelo approved these changes

2023-10-29 17:51 UTC, merged